#name of workflow
name: deploy-lambda
#triggers (object)
on:
  #event (object)
  push:
    #expects and array
    branches:
      - main
    #event for manual triggers, accessable in github console
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: dev
        required: false

#workflow jobs
jobs:
  #job name
  say-hello:
    #virtual machine environment
    runs-on: ubuntu-latest
    #job steps - expects yaml array
    steps:
      #step name
      - name: greet-user•
        #step job
        run: echo 'Hello Everybody!'

  #second job
  run-setup-and-checks:
    runs-on: ubuntu-latest
    steps:
      #first step - action from github marketplace actions
      - name: Checkout
        uses: actions/checkout@v3
      #second-step-install python
      - name: Setup Python
        #uses a github action to install python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.9"
      #third step - install make
      - name: install make
        #uses a terminal command
        run: sudo apt install make -y
      #fouth step - install Requirments
      - name: Install Requirements
        #uses make file to install dependancies
        run: make requirements
      #fith step - setup dev requirements
      - name: Setup Dev Requirements
        #runs dev-setup that is in make file
        run: make dev-setup
        #fith step - Run System Checks
      - name: Run System Checks
        #runs run-checks that is in make file
        run: make run-checks

  #third jobss
  deploy-lambda:
    needs: run-setup-and-checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # - name: Terraform Format
      #   working-directory: ./terraform
      #   id: fmt
      #   run: terraform fmt -check

      - name: Terraform Init
        working-directory: ./terraform
        id: init
        run: terraform init

      - name: Terraform Validate
        working-directory: ./terraform
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        working-directory: ./terraform
        id: plan
        run: terraform plan -no-color -input=false

      - name: Terraform Apply
        working-directory: ./terraform
        id: apply
        run: terraform apply -auto-approve -input=false
